pgd/urls.py
from django.conf.urls import *
#from django.views.generic.simple import direct_to_template
import settings
from django.contrib import admin
admin.autodiscover()

#from pgd import VERSION
#from pgd_splicer.models import pdb_select_settings

urlpatterns = patterns('',
    # Example:
    # (r'^pgd/', include('pgd.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #(r'^admin/(.*)', admin.site.root),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^search/', include('pgd_search.urls')),

    # Static pages:
    (r'^references/$', 'pgd.views.references'),
    (r'^contactus/$', 'pgd.views.contactus'),
    (r'^news/$', 'pgd.views.news'),
    
    #default url
    (r'^$','pgd.views.welcome'),
)

#The following is used to serve up local media files like images
#if settings.LOCAL_DEV:
baseurlregex = r'^static/(?P<path>.*)$'
urlpatterns += patterns('',
    (baseurlregex, 'django.views.static.serve', {'document_root':  settings.MEDIA_ROOT}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':  settings.MEDIA_ROOT}),
)

pgd_search/urls.py
from django.conf.urls import *
from pgd_search.search.views import search, saved, editSearch, help, qtiphelp, saveSearch, deleteSearch, protein_search, chi_help
from pgd_search.plot.views import renderToSVG, renderToPNG, plotDump, plot
from pgd_search.statistics.views import search_statistics, search_statistics_data, search_statistics_aa_data
from pgd_search.dump.views import dataDump
from pgd_search.browse.views import browse
from pgd_search.histogram.views import renderHist

urlpatterns = patterns('',
    (r'^$', search),
    (r'^protein_code/$', protein_search),
    (r'^results/$', plot),
    (r'^plot/svg/$', plot),
    (r'^plot/svg/render/$', renderToSVG),
    (r'^plot/png/$', renderToPNG),
    (r'^plot/dump/$', plotDump),
    (r'^statistics/$', search_statistics),
    (r'^statistics/data/$', search_statistics_data),
    (r'^statistics/aa/(\w+)$', search_statistics_aa_data),
    (r'^dump/$', dataDump),
    (r'^browse/$', browse),
    (r'^histogram/render/$', renderHist),
    (r'^saved/$', saved),
    (r'^help/$', help),
    (r'^chi_help/$', chi_help),
    (r'^qtiphelp/$', qtiphelp),
   
    #old style, for compatibility in the case of forgotton/overlooked links
    (r'^viewSearch/$', editSearch),
    (r'^viewSearch/(?P<search_id>\d+)/$', editSearch),
    (r'^edit/$', editSearch),
    (r'^edit/(?P<search_id>\d+)/$', editSearch),
    (r'^saveSearch/$', saveSearch),
    (r'^saveSearch/(?P<search_id>\d+)/$', saveSearch),
    (r'^deleteSearch/$', deleteSearch),
    (r'^deleteSearch/(?P<search_id>\d+)/$', deleteSearch),

    #new style 
    (r'^view/$', editSearch),
    (r'^(?P<search_id>\d+)/view/$', editSearch),
    (r'^edit/$', editSearch),
    (r'^(?P<search_id>\d+)/$', editSearch),
    (r'^save/$', saveSearch),
    (r'^(?P<search_id>\d+)/save/$', saveSearch),
    (r'^delete/$', deleteSearch),
    (r'^(?P<search_id>\d+)/delete/$', deleteSearch),
)

pgd_search/models.py
from exceptions import AttributeError
from math import ceil
import re
import cPickle

from django import forms
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User

from pgd_core.models import Protein,Residue
from pgd_constants import AA_CHOICES, AA_CHOICES_DICT, SS_CHOICES
from pgd_splicer.sidechain import bond_lengths_string_dict, bond_angles_string_dict
from pgd_core import residue_indexes


range_re = re.compile("(?<=[^-<>=])-")
comp_re  = re.compile("^([<>]=?)?")


class RDict(dict):
    """ Helper class for accessing a dict's properties as if they were member
    variables.  also return None for any value not found as a member
    """
    def __init__(self, dict_):
        self.update(dict_)
        super(dict, self).__init__()

    def __getitem__(self, k):
        try:
            return super(RDict, self).__getitem__(k)
        except KeyError:
            return None

    def __getattribute__(self, k):
        try:
            return super(dict, self).__getattribute__(k)
        except AttributeError:
            try:
                return self[k]
            except KeyError:
                return None


class Search(models.Model):
    """
    A query submitted by a user
    """
    dataset_version  = models.CharField(max_length='100')
    isPublic         = models.BooleanField(default=True)
    timestamp        = models.DateTimeField(null=True)
    title            = models.CharField(max_length='300')
    description      = models.CharField(max_length='5000')
    user             = models.ForeignKey(User, null=True)
    data_internal    = models.TextField()
    __data = None

    @property
    def data(self):
        if self.__data is None and self.data_internal:
            self.__data = cPickle.loads(str(self.data_internal))
        return self.__data

    @data.setter
    def data(self, value):
        self.__data = value
        self.data_internal = None

    @property
    def segmentLength(self):
        return int(self.data['residues'])


    @property
    def residues(self):
        """ iterates residues found in the search.  The objects yielded are
        self.data wrapped in a Segmenter.
        """
        data = self.data
        for i in range(self.segmentLength):
            yield Segmenter(data, i)



    def save(self):
        """ serialize parameters pre-save, object probably wont't be saved often """
        if self.data_internal is None and self.__data is not None:
            self.data_internal = cPickle.dumps(self.__data)
        super(Search, self).save()

    _querySet = None

    def querySet(self):
        """
        returns the query set that represents this search
        """
        # for now parse query every time.  otherwise the query results will be stored in the session
        return self.parse_search()

    # Return the segments matched by the search.
    def parse_search(self):

        # Start with all segments...
        query = Residue.objects.all()
        data = self.data
        if not data:
            # if no params return everything
            return query
        data = RDict(data)

        # ...filter by code lists...
        if data.proteins_i != None:
            #codes = data.proteins.replace(' ','').rstrip(',').split(',')
            data.proteins = data.proteins.replace(' ','').replace(',', '')
            codes = [data.proteins[i:i+4] for i in range(0, len(data.proteins), 4)]
            if data.proteins_i:
                query = query.filter(protein__code__in=codes)
            else:
                query = query.exclude(protein__code__in=codes)

        # ...filter by code lists...
        if data.resolutionMin != None:
            query = query.filter(protein__resolution__gte=data.resolutionMin)

        # ...filter by resolution...
        if data.resolutionMax != None:
            query = query.filter(protein__resolution__lte=data.resolutionMax)

        # ...filter by rfactor...
        if data.rfactorMin != None:
            query = query.filter(protein__rfactor__gte=data.rfactorMin)

        # ...filter by rfactor...
        if data.rfactorMax != None:
            query = query.filter(protein__rfactor__lte=data.rfactorMax)

        #...filter by rfree...
        if data.rfreeMin != None:
            query = query.filter(protein__rfree__gte=data.rfreeMin)

        # ...filter by rfree...
        if data.rfreeMax != None:
            query = query.filter(protein__rfree__lte=data.rfreeMax)


        # ...filter by threshold...
        if data.threshold != None:
            query = query.filter(protein__threshold__lte=data.threshold)

        # ...filter by query strings (for values and value ranges)...
        def compare(x,y):
            if x == y:
                return 0
            elif x < y:
                return -1
            return 1
        #residues = sorted(data.residues, compare, lambda x: abs(x.index) )


        indexes = residue_indexes(int(data.residues))
        for index in indexes: # iterate through all search residues in self
            search_res = Segmenter(data, index)

            # get field prefix for this residue
            if index == 0:
                seg_prefix = ''
            elif index < 0:
                seg_prefix = ''.join(['prev__' for i in range(index, 0)])
            else:
                seg_prefix = ''.join(['next__' for i in range(index)])

            # add isnull to ensure segment length is correct.  segments missing
            # a residue would be too short
            if seg_prefix != '':
                query = query.filter(**{'%sisnull' % seg_prefix:False})

            # get possible sidechain fields based on selected AA types
            sidechain_fields = []
            """for aa_type in filter(lambda x: x[1],search_res.aa.items()):
                aa_type_upper = aa_type[0].upper()
                for field in bond_lengths_string_dict[aa_type_upper]:
                    sidechain_fields.append('sidechain_%s__%s' % (aa_type_upper, field))
                for field in bond_angles_string_dict[aa_type_upper]:
                    sidechain_fields.append('sidechain_%s__%s' % (aa_type_upper, field))
            """

            # ...handle boolean values...
            #   (Filter on each binary field that is not set to NULL/None.)
            # XXX there don't appear to be any of these right now, xpr isn't on the form
            '''query = query.filter(**dict((
                    (seg_prefix+field, search_res.__dict__[field])
                    for field in (
                        'xpr',
                    ) if search_res.__dict__[field] != None
                )))
            '''

            # ...handle the '_int' values...
            #   ('_int' values are a series of booleans stored grouped in an integer.)
            for field,choices in filter(
                   # use only those (_int,_CHOICES) pairs with a '_include' value.
                   lambda x: search_res.__getitem__(x[0]+'_i') != None,
                   (
                       ('aa', AA_CHOICES),
                       ('ss', SS_CHOICES),
                   )
                ):
                query = query.__getattribute__(
                    # call either 'filter' or 'exclude', depending on the value of '_include'
                    'filter' if search_res.__getitem__(field+'_i') else 'exclude'
                )(
                    # check to see that the value of the segment residue is in the set of
                    # residues described in the '_int' of the search residue.
                    **{"%s%s__in" % (seg_prefix,field): search_res.__getitem__(field)}
                )

            # ...handle query strings...
            fields = filter(
                # use only the fields with a '_include' value.
                lambda x: search_res.__getitem__(x+'_i') != None,
                (
                    'a1',   'a2',   'a3',   'a4',   'a5',   'a6',   'a7',
                    'L1',   'L2',   'L3',   'L4',   'L5',
                    'phi',  'psi',  'ome',  'chi1', 'chi2', 'chi3', 'chi4', 'chi5',
                    'bm',   'bs',   'bg',
                    'h_bond_energy',
                    'zeta',
                )
            )
            query = self.filter_fields(fields, query, search_res, seg_prefix)

            # ... handle sidechain query strings ...
            sidechain_fields = []
            if search_res.aa:
                for aa_type in [AA_CHOICES_DICT[aa].upper() for aa in search_res.aa]:
                    if aa_type in bond_lengths_string_dict:
                        field_base = '%s__%%s' % aa_type
                        for field in bond_lengths_string_dict[aa_type]:
                            key = field_base % field
                            if search_res[key]:
                                sidechain_fields.append(key)

                        for field in bond_angles_string_dict[aa_type]:
                            key = field_base % field
                            if search_res[key]:
                                sidechain_fields.append(key)

            seg_prefix = '%ssidechain_' % seg_prefix
            query = self.filter_fields(sidechain_fields, query, search_res, seg_prefix)

        return query

    def filter_fields(self, fields, query, search_res, seg_prefix):
        """
        Filters the fields passed in
        """

        for field in fields:
            # seg_field is the name of the property of the given residue in the database
            seg_field = seg_prefix+field

            constraints = []

            for constraint in str(search_res.__getitem__(field)).split(','):

                # The constraint may be a range...
                if range_re.search(constraint):

                    min,max = [float(lim) for lim in range_re.split(constraint)]

                    limits = (
                        Q(**{seg_field+'__gte' : float(min)}),

pgd_search/browse/views.py
from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.paginator import Paginator, InvalidPage, EmptyPage
import math
import pickle
from pgd_search.views import settings_processor

"""
display search results in tabular form
"""
def browse(request):
    #saving globals as locals for speed
    lhex = hex
    lint = int

    # get search from session
    search = pickle.loads(request.session['search'])

    #generate iValues
    start = 0 - (search.segmentLength-1) / 2
    stop  = lint(math.ceil((search.segmentLength-1) / 2.0))+1
    iIndex = lint(math.ceil(settings.SEGMENT_SIZE/2.0)-1)

    #paginate
    segments = search.querySet().order_by('protein')
    paginator = Paginator(segments, 25) # Show 25 segments per page

    # Make sure page request is an int. If not, deliver first page.
    try:
        page = lint(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    # If page request (9999) is out of range, deliver last page of results.
    try:
        paginatedSegments = paginator.page(page)
    except (EmptyPage, InvalidPage):
        page = paginator.num_pages
        paginatedSegments = paginator.page(page)

    #generate a list of pages to display in the pagination bar
    pages = get_page_list(paginator, page)


    # use ranges for RGB to introduce colorful steps
    colors = [] 
    colorstop=settings.SEGMENT_SIZE/2
    rRange = (75,245);
    gRange = (180,245);
    bRange = (240,245);
    rInterval = round((rRange[1]-rRange[0])/colorstop)
    gInterval = round((gRange[1]-gRange[0])/colorstop)
    bInterval = round((bRange[1]-bRange[0])/colorstop)

    for i in range(colorstop-stop+1, colorstop+1):
        red = '%s' % lhex(lint(i*rInterval+rRange[0]))[2:] if i*rInterval+rRange[0] > 9 else '%02d' % lint(lhex(lint(i*rInterval+rRange[0]))[2:])
        green = '%s' % lhex(lint(i*gInterval+gRange[0]))[2:] if i*gInterval+gRange[0] > 9 else '%02d' % lint(lhex(lint(i*gInterval+gRange[0]))[2:])
        blue = '%s' % lhex(lint(i*bInterval+bRange[0]))[2:] if i*bInterval+bRange[0] > 9 else '%02d' % lint(lhex(lint(i*bInterval+bRange[0]))[2:])
        colors.append((red,green,blue))

    return render_to_response('browse.html', {
        'segments': paginatedSegments,
        'segmentSlice':'%i:%i'%(iIndex+start,iIndex+stop),
        'indexes':range(start,stop),
        'start':start,
        'stop':stop-1,
        'iIndex':iIndex,
        'pageStart':(page-1)*25,
        'indexColors':colors,
        'pages':pages,
        'segmentLength':search.segmentLength

    }, context_instance=RequestContext(request, processors=[settings_processor]))


def get_page_list(paginator, page=1):
    """
    Generate a list of pages used choose from to jump quickly to a page

    This generates a list that shows:
        * if near the start/end, up to 10 pages from the start/end
        * if in the middle first two and last two pages in addition to the
          +/- 5 from the current page
       * if num_pages<10 - only one list of pages is shown
       * if num_pages==11 then the list is statically generated because this
         list size results in wierd results for the standard logic that generates
         the lists.
    """

    if paginator.num_pages < 11:
        # special case: only one list of values
        pages = (range(1,paginator.num_pages+1),)
    elif paginator.num_pages == 11:
        # special case: lists are static
        pages = ([1,2,3,4,5,6,7,8,9,10], None, [11])
    else:
        # normal case
        start = [i for i in range(1, 11 if page < 8 and page < paginator.num_pages-6 else 3)]
        middle = [i for i in range(page-5,page+5)] if page > 7 and page < paginator.num_pages-6 else None
        end = [i for i in range(paginator.num_pages-(1 if page < paginator.num_pages-6 else 9), paginator.num_pages+1)]
        pages = (start, middle, end)

    return pages

pgd_search/dump/views.py
from django.http import StreamingHttpResponse
from DataDump import Dump
import pickle

def dataDump(request):
    """
    render the results of the search as a TSV (tab separated file)
    and return it to the user as a download
    """
    dump = Dump(pickle.loads(request.session['search']))
    response = StreamingHttpResponse(dump, content_type="text/tab-separated-values")
    response['Content-Disposition'] = 'attachment; filename="data.tsv"'

    return response

pgd_search/templates/angles_helper.html
{% extends 'base.html' %}


{% block head %}
    <style>
        #outer {
            border:2px solid #AAAAAA;
            -moz-border-radius:5px;
            width:185px;
        }
        
        #canvas {
            margin-left:auto;
            margin-right:auto;
            width:165px;
        }
        
        input {
            width:400px;
        }
    </style>

    <script type="text/javascript" src="http://github.com/DmitryBaranovskiy/raphael/blob/master/raphael-min.js?raw=true"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}js/jquery.qtip-1.0.0-rc3.min.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}js/DejaVu_400.font.full.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <script type="text/javascript">
    
        var r = undefined;
        var _angles = undefined;
        var rad = Math.PI/180;
        var cur = undefined;

        function draw_arc(cx,cy,start,end, R) {
            var x1 = cx - R * Math.cos(-start * rad),
            x2 = cx - R * Math.cos(-end * rad),
            y1 = cy - R * Math.sin(-start * rad),
            y2 = cy - R * Math.sin(-end * rad);
            if (-180==start && 180==end) {
                path = ["M", 70.001, 90.001 - R, "A", R, R, 0, 1, 1, 69.99, 90.001 - R].join();
            } else {
                path = ["M", x1, y1, "A", R, R, 0, +(end - start > 180), 0, x2, y2].join();
                console.log(path);
            }
            return r.path(path).attr({stroke: '#008800', "stroke-width": 5});
        }

        function draw_arc(cx,cy,start,end, R) {
            var x1 = cx - R * Math.cos(-start * rad),
            x2 = cx - R * Math.cos(-end * rad),
            y1 = cy - R * Math.sin(-start * rad),
            y2 = cy - R * Math.sin(-end * rad);
            if (-180==start && 180==end) {
                path = ["M", 70.001, 90.001 - R, "A", R, R, 0, 1, 1, 69.99, 90.001 - R].join();
            } else {
                path = ["M",cx,cy,"L", x1, y1, "A", R, R, 0, +(end - start > 180), 0, x2, y2, "z"].join();
                console.log(path);
            }
            return r.path(path).attr({stroke: '#004400', fill:'#c2e192', "stroke-width": 1, opacity:.8});
        }

        function angles(list){
            if (_angles != undefined) {
                for (i in _angles){ _angles[i].remove()}
            }
            base = 100
            _angles = [];
            for (i in list) {
                _angles.push(draw_arc(80,90,list[i][0]+180,list[i][1]+180, 40));
            }
        }
    
        function match(val){
            m = val.match(/^(-?(([1-9]\d*|0)(\.\d+)?|(\.\d+))(--?(([1-9]\d*|0)(\.\d+)?|(\.\d+)))?|[<>]=?-?(([1-9]\d*|0)(\.\d+)?|(\.\d+)))(,(-?(([1-9]\d*|0)(\.\d+)?|(\.\d+))(--?(([1-9]\d*|0)(\.\d+)?|(\.\d+)))?|[<>]=?-?(([1-9]\d*|0)(\.\d+)?|(\.\d+))))*$/)
            if (!m){
                return [];
            }
            
            vals = val.split(',');
            processed = [];
            for (i in vals){
                v = vals[i];
                if (v.indexOf('<=')!=-1) {
                    console.log(2);
                    processed.push([-180, parseFloat(v.substring(2))]);
                } else if (v.indexOf('>=')!=-1) {
                    console.log(3);
                    processed.push([parseFloat(v.substring(2)), 180]);
                } else if (v.indexOf('<')!=-1) {
                    console.log(5);
                    processed.push([-180, parseFloat(v.substring(1))]);
                } else if (v.indexOf('>')!=-1) {
                    console.log(6);
                    processed.push([parseFloat(v.substring(1)), 180]);
                } else if (v.indexOf('-',1)!=-1) {
                    console.log(1);
                    z = v.indexOf('-',1);
                    v1 = parseFloat(v.substring(0,z));
                    v2 = parseFloat(v.substring(z+1));
                    processed.push([v1,v2]);
                
                } else {
                    console.log(4);
                    v = parseFloat(v);
                    processed.push([v,v+1]);
                }
            }
            return processed;
        }
    
        $(document).ready(function(){
            r = Raphael("canvas", 170, 175);
            //font = r.getFont("DejaVu");
            param = {stroke: "#000", "stroke-width": 1, "stroke-dasharray":"- "}
            
            x = 80;
            y = 90;
            radius = 30;
            r.circle(x,y,radius).attr({stroke: "#AAAAAA", "stroke-width": 1, "stroke-dasharray":"- "});
            
            r.path("M"+x+" "+(y-radius-40)+"L"+x+ " " +(y+radius+40)).attr(param);
            r.path("M"+(x-radius-50)+" "+y+"L"+(x+radius+40)+ " " +y).attr(param);
            r.text(x+radius+48, y, "0");
            r.text(x, y-radius-48, "90");
            r.text(x, y+radius+45, "-90");
            r.text(x-radius-35, y-10, "180");
            r.text(x-radius-35, y+12, "-180");
            
            $('#val').keyup(function(){
                val = $(this).val()
                if (cur==val){return;}
                m = match(val);
                angles(m);
                cur = val;
            });
        });
    </script>
{% endblock %}


{% block content %}
    <div id="outer">
        <div id="canvas"></div>
    </div>
    
    <input id="val" size="80">
{% endblock %}

pgd_search/templates/chi_help.html
{% extends 'search_base.html' %}

{% block head %}
    <style>
        #content {
            width:700px;
        }

        #table_of_contents {
             margin-bottom: 30px;
             padding-left:30px;
        }

        #table_of_contents li a {
            color: #000;
        }

        .section {
            border-bottom: 2px solid gray;
            margin-bottom: 50px;
        }

        .section a {
            border-bottom:1px blue dotted;
            text-decoration:none;
        }

        .section a:hover {
            border-bottom:1px blue solid;
            color:#1854d0;
        }

        .section h2 {
            border-bottom: 2px solid gray;
            font-size:25px;
            margin-bottom:10px;
        }

        .section h2 a, .section h2 a:hover{
            border: 0;
            color:#1854d0;
            font-size:25px;
            text-decoration:none;
        }

        .subsection h3 {
            border:0;
            color:#1854d0;
            font-size:16px;
            margin-top:20px;
        }

        .section p {
            margin-bottom:20px;
        }

        .section ul li{
            margin-bottom:10px;
            margin-left: 40px;
        }

        a.top {
            border:0;
            color:#000;
            font-style:italic;
            margin-top:10px;
        }



        a.top:hover {
            border:0;
            color:#1854d0;
            font-style:italic;
            margin-top:10px;
        }

    </style>
{% endblock %}

{% block content %}
<p>This is the help for &chi;</p>
{% for protein in PROTEIN_ORDER %}
<p>protein</p>
{% endfor %}
{% endblock content %}

pgd_search/templates/saveSearch.html
{% extends "base.html" %}
{% block head %}

<style>

    div#content{
        padding:5px;
        width:1000px;
        margin-left:auto;
        margin-right:auto;
    }
    div#save_form{

    }
    label{
        float:left;
    }
    .form_label{
        font-weight:bold;
    }
    #id_description{
        float:left;
    }
    div.errors{
        float:right;
    }
    div#errors {
        color:red;
        font-weight:bold;
        text-align:left;
        margin-left:25px;
        margin-bottom:30px;
    }

    ul.errors {
        color:red;
        margin-left:30px;
    }

    ul.errorlist {
        margin-left:45px;
        font-weight:normal;
        color:red;
    }
    td{
        padding:6px;
        margin: 6px;
    }
    td#save{
        text-align:center;
    }
    td#public_option{
        border-style:dashed;
        border-color:#D9D9D9;
        border-width:1px;
        background-color:#E8E8E8;
    }
    #id_isPublic{
        float:right;
        margin: 6px;
    }
    th#label_column{
        width:400px;
    }
    th#field_column{
        width:600px;
    }
    input#id_title{
        width:100%;
        float:left;
    }
    textarea{
        background-color: #ffffff;
        border: 1px solid #d4d4d4;
        font-size: 12px;
        font-weight:2;
        line-height:15px;
        padding:1px;
        width:100%;
    }
    p{
        text-align:center;
    }
</style>

{% endblock %}

{% block content %}
{% if session.search or form.id %}
<div id="save_form">
    <form method="post" action=".">{% csrf_token %}
        <table>
        <th id="label_column"></th>
        <th id="field_column"></th>
            <tr>
                <td><span class="form_label">{{ form.title.label }}</span>
                <br>
                A brief description of the search. Maximum 300 characters.
                </td>
                <td>{{ form.title }}</td>
            </tr>
            <tr>
                <td><span class="form_label">{{ form.description.label }}</span>
                     <br>
                    A more in depth description of the search. Maximum 5000 characters.
                </td>
                <td>{{ form.description }}</td>
            </tr>
            <tr>
                <td id="public_option" colspan="2"><span class="form_label">{{ form.isPublic.label }}</span>{{ form.isPublic }}
                    <br>
                    Allows other people to view the search, but not to edit anything about it. Use this to share searches with a link to other people.
                    By default, all searches are private and inaccessible to others.
                </td>
            </tr>
            <tr>
                <td id="save" colspan="2"><input type="submit" value="Save" /></td>
            </tr>
        </table>
    </form>
</div>
<div id="errors">{{ form.errors }}</div>
{% else %}
<p>There is no search to save.</p>
{% endif %}
{% endblock %}

pgd_search/templates/search_base.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/search.css" />
{% endblock %}